{% set name = "mms-python-client" %}
{% set version = "3.4.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c6c705df393aef09b583b11f2e36d21e9ed60e31a4ac05a3d0f6af09935df051" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil
  run:
    - python
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: Model Management Service
  description: 'Model Management System (MMS) is a version control system for structured data. It exposes model information through RESTful web services that can be used for CRUD operations, branching,
    and tagging of the model repository.  # noqa: E501'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
