#!/bin/bash

if [ "$#" -eq 1 ]; then
  echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$1 -v "http://localhost:8080/alfresco/service/workspaces/master/configurations"
  curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$1 -v "http://localhost:8080/alfresco/service/workspaces/master/configurations"
elif [ "$#" -eq 2 ]; then
  echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$2 -v "http://localhost:8080/alfresco/service/workspaces/$1/configurations"
  curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$2 -v "http://localhost:8080/alfresco/service/workspaces/$1/configurations"
elif [ "$#" -eq 3 ]; then
  echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$3 -v "http://localhost:8080/alfresco/service/workspaces/$1/sites/$2/configurations"
  curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$3 -v "http://localhost:8080/alfresco/service/workspaces/$1/sites/$2/configurations"
fi;
