#!/bin/bash

echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/refs/master/elements/$1?evaluate=true"

curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/refs/master/elements/$1?evaluate=true"
