#!/bin/bash

if [ "$#" -eq 2 ] && [ $2 = 'recursive' ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/elements/$1?recurse=true"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/elements/$1?recurse=true"
elif [ "$#" -eq 2 ]; then
  echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/$1/elements/$2"
  curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/$1/elements/$2"
elif [ "$#" -eq 3 ] && [ $3 = 'recursive' ]; then
  echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/$1/elements/$2?recurse=true"
  curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/$1/elements/$2?recurse=true"
elif [ "$#" -eq 1 ]; then
  echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/master/elements/$1"
  curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/master/elements/$1"
else
  echo "wrong number of args"
  echo "usage: $0 [<workspace>] <elementId> [recurse]"
fi;


